### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by PerfectZyx** [LZhengyu/MSCRED#1]
Can you describe the configured environment?For example, the TensorFlow version.

**Comment by LZhengyu** [comment]
> Can you describe the configured environment?For example, the TensorFlow version.

I used tensorflow 1.8.0 cpu version, python 3.6

**Comment by PerfectZyx** [comment]
好的，非常感谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LZhengyu/MSCRED"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 上午10:25
收件人:&nbsp;"LZhengyu/MSCRED"<MSCRED@noreply.github.com&gt;;
抄送:&nbsp;"Zyx"<434317753@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LZhengyu/MSCRED] Environment (#1)





  
Can you describe the configured environment?For example, the TensorFlow version.
  
I used tensorflow 1.8.0 cpu version, python 3.6

**Comment by PerfectZyx** [comment]
> > Can you describe the configured environment?For example, the TensorFlow version.
> 
> I used tensorflow 1.8.0 cpu version, python 3.6

Thank you very much
